services:

  idoncare-frontend:
    user: root
    container_name: idoncare-frontend
    build: ./frontend
    image: idoncare/idoncare-frontend
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt/live/j11a603.p.ssafy.io:/etc/letsencrypt/live/j11a603.p.ssafy.io
      - /etc/letsencrypt/archive/j11a603.p.ssafy.io:/etc/letsencrypt/archive/j11a603.p.ssafy.io 


    environment:
      TZ: Asia/Seoul

