spring:
  profiles:
    active: prod
  security:
    user:
      name: user
      password: 1234
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: alkjdshflekwjthaklsdjfhbzcvnaklsjghwetiuoqalhkdsfjdjsfhkaebasdlkjfhwejklrhasdlkjfhsdfljk
  refresh_token:
    expiration_time: 604800  # Refresh token 만료시간 (7일 = 604800초)
  access_token:
    expiration_time: 3600 # Access token 만료시간 (1시간 = 3600초)
